

set(Minecraft_SOURCES
	source/Biome.cpp
source/Biome.h
source/biomeDefines.h
source/BlockId.h
source/BlockLookup.cpp
source/BlockLookup.h
source/Camera.cpp
source/Camera.h
source/Chunk.cpp
source/Chunk.h
source/Creature.cpp
source/Creature.h
source/define.h
source/DynamicBlock.h
source/Enemy.cpp
source/Enemy.h
source/Face.h
source/glmType.h
source/Graphics.cpp
source/Graphics.h
source/InputManager.cpp
source/InputManager.h
source/Inventory.cpp
source/Inventory.h
source/Item.cpp
source/Item.h
source/Main.cpp
source/Mesh.cpp
source/Mesh.h
source/Minecraft.cpp
source/Minecraft.h
source/Noise.cpp
source/Noise.h
source/Physics.cpp
source/Physics.h
source/Player.cpp
source/Player.h
source/Recipe.cpp
source/Recipe.h
source/StateMachine.h
source/TargetBlock.h
source/Texture.cpp
source/Texture.h
source/TextureManager.cpp
source/TextureManager.h
source/Trigo.h
source/UI.cpp
source/UI.h
source/World.cpp
source/World.h
	shaders/Block.frag
shaders/Block.geom
shaders/Block.vert
shaders/Entity.vert
shaders/Falling.vert
shaders/Fluid.geom
shaders/Item.frag
shaders/Item.vert
shaders/Simple.frag
shaders/Target.geom
	)
