#pragma once

#include "biomeDefines.h"
#include "BlockId.h"

namespace Minecraft
{
	struct Biome
	{
		const int avgHeight;
		const int heightAmplitude;
		const int heightFrequency;
		const int heightOctaves;
		const int surfaceBlock;
		const int surfaceDepth;
		const int subsurfaceBlock;
		const int subsurfaceDepth;
		const float lakeDensity;
		const float treeDensity;
		const float flowerDensity;
	};

	static const Biome s_PLAINS
	{
		PLAINS_AVG_HEIGHT,
		PLAINS_HEIGHT_AMPLITUDE,
		PLAINS_HEIGHT_FREQUENCY,
		PLAINS_HEIGHT_OCTAVES,
		PLAINS_SURFACE_BLOCK,
		PLAINS_SURFACE_DEPTH,
		PLAINS_SUBSURFACE_BLOCK,
		PLAINS_SUBSURFACE_DEPTH,
		PLAINS_LAKE_DENSITY,
		PLAINS_TREE_DENSITY,
		PLAINS_FLOWER_DENSITY
	};

	static const Biome s_OCEAN
	{
		OCEAN_AVG_HEIGHT,
		OCEAN_HEIGHT_AMPLITUDE,
		OCEAN_HEIGHT_FREQUENCY,
		OCEAN_HEIGHT_OCTAVES,
		OCEAN_SURFACE_BLOCK,
		OCEAN_SURFACE_DEPTH,
		OCEAN_SUBSURFACE_BLOCK,
		OCEAN_SUBSURFACE_DEPTH,
		OCEAN_LAKE_DENSITY,
		OCEAN_TREE_DENSITY,
		OCEAN_FLOWER_DENSITY
	};

	static const Biome s_MOUNTAIN
	{
		MOUNTAIN_AVG_HEIGHT,
		MOUNTAIN_HEIGHT_AMPLITUDE,
		MOUNTAIN_HEIGHT_FREQUENCY,
		MOUNTAIN_HEIGHT_OCTAVES,
		MOUNTAIN_SURFACE_BLOCK,
		MOUNTAIN_SURFACE_DEPTH,
		MOUNTAIN_SUBSURFACE_BLOCK,
		MOUNTAIN_SUBSURFACE_DEPTH,
		MOUNTAIN_LAKE_DENSITY,
		MOUNTAIN_TREE_DENSITY,
		MOUNTAIN_FLOWER_DENSITY
	};

	static const Biome s_FOREST
	{
		FOREST_AVG_HEIGHT,
		FOREST_HEIGHT_AMPLITUDE,
		FOREST_HEIGHT_FREQUENCY,
		FOREST_HEIGHT_OCTAVES,
		FOREST_SURFACE_BLOCK,
		FOREST_SURFACE_DEPTH,
		FOREST_SUBSURFACE_BLOCK,
		FOREST_SUBSURFACE_DEPTH,
		FOREST_LAKE_DENSITY,
		FOREST_TREE_DENSITY,
		FOREST_FLOWER_DENSITY
	};

	static const Biome s_DESERT
	{
		DESERT_AVG_HEIGHT,
		DESERT_HEIGHT_AMPLITUDE,
		DESERT_HEIGHT_FREQUENCY,
		DESERT_HEIGHT_OCTAVES,
		DESERT_SURFACE_BLOCK,
		DESERT_SURFACE_DEPTH,
		DESERT_SUBSURFACE_BLOCK,
		DESERT_SUBSURFACE_DEPTH,
		DESERT_LAKE_DENSITY,
		DESERT_TREE_DENSITY,
		DESERT_FLOWER_DENSITY
	};

	const Biome& GetStaticBiome(BiomeType type);
}