# pragma once

// Location for all biome definition values

enum class BiomeType : int
{
	PLAINS,
	OCEAN,
	MOUNTAIN,
	FOREST,
	DESERT,

	NUM_BIOMES
};

/*
	Plains
*/

#define PLAINS_AVG_HEIGHT 70
#define PLAINS_HEIGHT_AMPLITUDE 40
#define PLAINS_HEIGHT_FREQUENCY 20
#define PLAINS_HEIGHT_OCTAVES 6
#define PLAINS_SURFACE_BLOCK Minecraft::BlockId::GRASS
#define PLAINS_SURFACE_DEPTH 1
#define PLAINS_SUBSURFACE_BLOCK Minecraft::BlockId::DIRT
#define PLAINS_SUBSURFACE_DEPTH 4
#define PLAINS_LAKE_DENSITY 0.1f
#define PLAINS_TREE_DENSITY 0.25f
#define PLAINS_FLOWER_DENSITY 0.4f

/*
	Ocean
*/

#define OCEAN_AVG_HEIGHT 50
#define OCEAN_HEIGHT_AMPLITUDE 50
#define OCEAN_HEIGHT_FREQUENCY 20
#define OCEAN_HEIGHT_OCTAVES 7
#define OCEAN_SURFACE_BLOCK Minecraft::BlockId::SAND
#define OCEAN_SURFACE_DEPTH 2
#define OCEAN_SUBSURFACE_BLOCK Minecraft::BlockId::DIRT
#define OCEAN_SUBSURFACE_DEPTH 2
#define OCEAN_LAKE_DENSITY 0.f
#define OCEAN_TREE_DENSITY 0.f
#define OCEAN_FLOWER_DENSITY 0.f

/*
	Mountain
*/

#define MOUNTAIN_AVG_HEIGHT 110
#define MOUNTAIN_HEIGHT_AMPLITUDE 90
#define MOUNTAIN_HEIGHT_FREQUENCY 20
#define MOUNTAIN_HEIGHT_OCTAVES 8
#define MOUNTAIN_SURFACE_BLOCK Minecraft::BlockId::GRASS
#define MOUNTAIN_SURFACE_DEPTH 1
#define MOUNTAIN_SUBSURFACE_BLOCK Minecraft::BlockId::STONE
#define MOUNTAIN_SUBSURFACE_DEPTH 0
#define MOUNTAIN_LAKE_DENSITY 0
#define MOUNTAIN_TREE_DENSITY 0.1f
#define MOUNTAIN_FLOWER_DENSITY 0.1f

/*
	Forest
*/

#define FOREST_AVG_HEIGHT 75
#define FOREST_HEIGHT_AMPLITUDE 40
#define FOREST_HEIGHT_FREQUENCY 20
#define FOREST_HEIGHT_OCTAVES 6
#define FOREST_SURFACE_BLOCK Minecraft::BlockId::GRASS
#define FOREST_SURFACE_DEPTH 1
#define FOREST_SUBSURFACE_BLOCK Minecraft::BlockId::DIRT
#define FOREST_SUBSURFACE_DEPTH 4
#define FOREST_LAKE_DENSITY 0.1f
#define FOREST_TREE_DENSITY 4.f
#define FOREST_FLOWER_DENSITY 0.1f

/*
	Desert
*/

#define DESERT_AVG_HEIGHT 70
#define DESERT_HEIGHT_AMPLITUDE 30
#define DESERT_HEIGHT_FREQUENCY 20
#define DESERT_HEIGHT_OCTAVES 6
#define DESERT_SURFACE_BLOCK Minecraft::BlockId::SAND
#define DESERT_SURFACE_DEPTH 6
#define DESERT_SUBSURFACE_BLOCK Minecraft::BlockId::STONE
#define DESERT_SUBSURFACE_DEPTH 0
#define DESERT_LAKE_DENSITY 0.f
#define DESERT_TREE_DENSITY 0.f
#define DESERT_FLOWER_DENSITY 0.f